name: Deploy to Amazon S3

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean install dependencies and build client
      run: |
        npm i
        npm run build
      env:
        VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        VITE_AWS_IMAGES: ${{ secrets.AWS_IMAGES }}
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to S3
      uses: reggionick/s3-deploy@v4
      with:
        folder: dist
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.AWS_REGION }}
        private: true
        delete-removed: true
